### ISSUE TITLE
MongoDB Windows 服务安装下 replica 结构搭建

### ISSUE THREAD

**Issue by kbillows** [kbillows/logs#5]
### Windows 服务的安装与卸载

安装 Windows 服务执行如下命令：
```
mongod.exe --bind_ip yourIPadress --logpath "C:\data\dbConf\mongodb.log" --logappend --dbpath "C:\data\db" --port yourPortNumber --serviceName "YourServiceName" --serviceDisplayName "YourServiceName" --install
```
eg.
```
mongod.exe --bind_ip 127.0.0.1 --logpath "C:\MongoDB\secondary3\log\mongodb.log" --logappend --dbpath "C:\MongoDB\secondary3\data" --port 29035 --serviceName "MongoDB_3.4.2_secondary3" --serviceDisplayName "mongo-sec3(29035)" --install
```
_注意：与旧版本不同的是，3.x的日志的配置是要一个具体的.log文件，而不再是一个目录就行了_

卸载 Windows 服务执行如下命令：
```
mongod --remove --serviceName "MongoDB_3.4.2_secondary3"
```

### 搭建 replica  结构

1. 在同一级目录下创建primary、secondary1、secnodary2...等目录；
2. 在每个目录下创建data、log目录和mongod.cfg（配置文件）
3. 打开每个mongod.cfg，添加如下配置代码：
```
systemLog:
   quiet: false
   destination: file
   path: C:\\MongoDB\primary\\log\\mongodb.log
   logAppend: true
   logRotate: rename
net:
   port: 29031
   maxIncomingConnections: 65536  
   wireObjectCheck: true  
   ipv6: false 
storage:
   dbPath: C:\\MongoDB\primary\\data
   indexBuildRetry: true
   directoryPerDB: true
replication:
   oplogSizeMB: 20
   replSetName: rs1
--注意修改不同文件中 systemLog 节中的 path 值，net 节中的 port 值和 storage 节点中 dbPath 的值。
```

4. 创建完上述的几个配置文件后，分别执行以下命令，完成每个实例的配置
```
mongod --config C:\MongoDB\secondaryX\mongod.cfg
```

5. replica 节点目录创建后，需要指定指定哪个是主的，选择需要指定为primary的实例进入，比如以29031为主，执行以下mongo命令：
```
\bin\mongo -port 29031
-- 等待连接完毕
rs.initiate() --会得到machineNamee及port信息
rs.config() --会指定哪一个是primary的
rs.add("machineName":29032) --添加secondary1
rs.add("machineName":29033) --添加secondary2
rs.status() --查看设置好之后的状态
/*
说明：29031,29032,29033是在安装不同mongoDB实例时指定的端口号。
*/
```

### 搭建 replication set 的步骤
1. 停掉3个mongodb的服务
2. 卸载3个mongodb的服务
3. 修改三个目录的配置文件，加上replication节点
4. 重新安装3个mongodb服务
